//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Language {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Language.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceder.
        /// </summary>
        internal static string Acceder {
            get {
                return ResourceManager.GetString("Acceder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar.
        /// </summary>
        internal static string Administrar {
            get {
                return ResourceManager.GetString("Administrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajuste de Inventario.
        /// </summary>
        internal static string Ajuste {
            get {
                return ResourceManager.GetString("Ajuste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articulo.
        /// </summary>
        internal static string Articulo {
            get {
                return ResourceManager.GetString("Articulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículos.
        /// </summary>
        internal static string Articulos {
            get {
                return ResourceManager.GetString("Articulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención.
        /// </summary>
        internal static string Atencion {
            get {
                return ResourceManager.GetString("Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay campos sin completar..
        /// </summary>
        internal static string AtLogInEmptyorNull {
            get {
                return ResourceManager.GetString("AtLogInEmptyorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos, verifique..
        /// </summary>
        internal static string AtLogInIncorrecto {
            get {
                return ResourceManager.GetString("AtLogInIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad total.
        /// </summary>
        internal static string CantidadTotal {
            get {
                return ResourceManager.GetString("CantidadTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre.
        /// </summary>
        internal static string Cierre {
            get {
                return ResourceManager.GetString("Cierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre Definitivo.
        /// </summary>
        internal static string CierreDef {
            get {
                return ResourceManager.GetString("CierreDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre Parcial.
        /// </summary>
        internal static string CierreParcial {
            get {
                return ResourceManager.GetString("CierreParcial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completar Cantidad.
        /// </summary>
        internal static string ComplCant {
            get {
                return ResourceManager.GetString("ComplCant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobante.
        /// </summary>
        internal static string Comprobante {
            get {
                return ResourceManager.GetString("Comprobante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Comprobante.
        /// </summary>
        internal static string ComprobanteDetalle {
            get {
                return ResourceManager.GetString("ComprobanteDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comprobante ha sido generado exitosamente..
        /// </summary>
        internal static string ComprobanteGenerado {
            get {
                return ResourceManager.GetString("ComprobanteGenerado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string Conf {
            get {
                return ResourceManager.GetString("Conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depósito.
        /// </summary>
        internal static string Deposito {
            get {
                return ResourceManager.GetString("Deposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destinatario.
        /// </summary>
        internal static string Destinatario {
            get {
                return ResourceManager.GetString("Destinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino.
        /// </summary>
        internal static string Destino {
            get {
                return ResourceManager.GetString("Destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duplicado.
        /// </summary>
        internal static string Duplicado {
            get {
                return ResourceManager.GetString("Duplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe completar todos los campos..
        /// </summary>
        internal static string ErrorCampoVacio {
            get {
                return ResourceManager.GetString("ErrorCampoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar líneas..
        /// </summary>
        internal static string ErrorFaltanLineas {
            get {
                return ResourceManager.GetString("ErrorFaltanLineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede ingresar una fecha menor a la actual..
        /// </summary>
        internal static string ErrorFechaMenAct {
            get {
                return ResourceManager.GetString("ErrorFechaMenAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron registros..
        /// </summary>
        internal static string ErrorSinRegistros {
            get {
                return ResourceManager.GetString("ErrorSinRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Error de integridad! El sistema se encuentra inoperable. Contacte con el administrador del sistema..
        /// </summary>
        internal static string ErrorSistemaCorrupto {
            get {
                return ResourceManager.GetString("ErrorSistemaCorrupto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar solo números..
        /// </summary>
        internal static string ErrorValorNumerico {
            get {
                return ResourceManager.GetString("ErrorValorNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Etiquetas.
        /// </summary>
        internal static string Etiq {
            get {
                return ResourceManager.GetString("Etiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Etiquetas generadas.
        /// </summary>
        internal static string EtiquetasGeneradas {
            get {
                return ResourceManager.GetString("EtiquetasGeneradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generado.
        /// </summary>
        internal static string Generado {
            get {
                return ResourceManager.GetString("Generado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial x Item.
        /// </summary>
        internal static string HxI {
            get {
                return ResourceManager.GetString("HxI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impresión de Comprobante.
        /// </summary>
        internal static string ImpComprobante {
            get {
                return ResourceManager.GetString("ImpComprobante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impresión de Etiquetas.
        /// </summary>
        internal static string ImpEtiq {
            get {
                return ResourceManager.GetString("ImpEtiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar.
        /// </summary>
        internal static string Importar {
            get {
                return ResourceManager.GetString("Importar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        internal static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informe de Recepción.
        /// </summary>
        internal static string InformeRecepcion {
            get {
                return ResourceManager.GetString("InformeRecepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventario.
        /// </summary>
        internal static string Inventario {
            get {
                return ResourceManager.GetString("Inventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventario x Cliente.
        /// </summary>
        internal static string IxC {
            get {
                return ResourceManager.GetString("IxC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Layout.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Letra.
        /// </summary>
        internal static string Letra {
            get {
                return ResourceManager.GetString("Letra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Linea.
        /// </summary>
        internal static string Linea {
            get {
                return ResourceManager.GetString("Linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado Stock.
        /// </summary>
        internal static string ListStock {
            get {
                return ResourceManager.GetString("ListStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ingresó al sistema..
        /// </summary>
        internal static string loginCorrecto {
            get {
                return ResourceManager.GetString("loginCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Confirmados.
        /// </summary>
        internal static string MostrarConf {
            get {
                return ResourceManager.GetString("MostrarConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo.
        /// </summary>
        internal static string Motivo {
            get {
                return ResourceManager.GetString("Motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimientos.
        /// </summary>
        internal static string Movimientos {
            get {
                return ResourceManager.GetString("Movimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Comprobante.
        /// </summary>
        internal static string NumeroComprobante {
            get {
                return ResourceManager.GetString("NumeroComprobante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación.
        /// </summary>
        internal static string Observacion {
            get {
                return ResourceManager.GetString("Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen.
        /// </summary>
        internal static string Origen {
            get {
                return ResourceManager.GetString("Origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Original.
        /// </summary>
        internal static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Picking.
        /// </summary>
        internal static string Picking {
            get {
                return ResourceManager.GetString("Picking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso correcto..
        /// </summary>
        internal static string ProcesoCorrecto {
            get {
                return ResourceManager.GetString("ProcesoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posiciones x Estado.
        /// </summary>
        internal static string PxE {
            get {
                return ResourceManager.GetString("PxE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recepción.
        /// </summary>
        internal static string Recepcion {
            get {
                return ResourceManager.GetString("Recepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remito.
        /// </summary>
        internal static string Remito {
            get {
                return ResourceManager.GetString("Remito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        internal static string Reportes {
            get {
                return ResourceManager.GetString("Reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scaneo.
        /// </summary>
        internal static string Scaneo {
            get {
                return ResourceManager.GetString("Scaneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar copia.
        /// </summary>
        internal static string SeleCopia {
            get {
                return ResourceManager.GetString("SeleCopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucursal.
        /// </summary>
        internal static string Sucursal {
            get {
                return ResourceManager.GetString("Sucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transferencia.
        /// </summary>
        internal static string Transferencia {
            get {
                return ResourceManager.GetString("Transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triplicado.
        /// </summary>
        internal static string Triplicado {
            get {
                return ResourceManager.GetString("Triplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
